# Current time stamp
std_msgs/Time            stamp


# Current mode of operation
uint8           mode

# Messages sent
uint16          messages_sent

# Messages received
uint16          messages_received

# Messages dropped
uint16          messages_dropped

# External actuation messages
uint16          messages_external

# Averaged frequency for reception 
uint16          frequency_reception

# Averaged frequency for actuation
uint16          frequency_actuation
